### ISSUE TITLE
mongo-statsd-backend crashes statsd daemon

### ISSUE THREAD

**Issue by etiennep** [dynmeth/mongo-statsd-backend#2]
When using with statsd version 0.5.0 I get the following stack trace:

connection_queue.drain()

/usr/lib/node_modules/mongo-statsd-backend/node_modules/mongodb/lib/mongodb/connection/server.js:524
        throw err;
              ^
Error: Callback was already called.
    at i (/usr/lib/node_modules/mongo-statsd-backend/node_modules/async/lib/async.js:22:31)
    at onFlush (/usr/lib/node_modules/mongo-statsd-backend/lib/index.js:155:8)
    at insert (/usr/lib/node_modules/mongo-statsd-backend/lib/index.js:126:8)
    at insertAll (/usr/lib/node_modules/mongo-statsd-backend/node_modules/mongodb/lib/mongodb/collection.js:343:12)
    at Collection.insert (/usr/lib/node_modules/mongo-statsd-backend/node_modules/mongodb/lib/mongodb/collection.js:91:3)
    at insert (/usr/lib/node_modules/mongo-statsd-backend/lib/index.js:122:10)
    at Db.createCollection (/usr/lib/node_modules/mongo-statsd-backend/node_modules/mongodb/lib/mongodb/db.js:872:16)
    at Db._executeQueryCommand (/usr/lib/node_modules/mongo-statsd-backend/node_modules/mongodb/lib/mongodb/db.js:1692:5)
    at g (events.js:192:14)
    at EventEmitter.emit (events.js:126:20)

The issue does not happen with 0.4.0.

**Comment by ebenoist** [comment]
I'm getting the same issue. Any idea where I should dig?

**Comment by dbhowell** [comment]
I haven't had a good look at this (I haven't been able to reproduce it). I'm re-factoring the backend since statsd has made such big changes in 0.5.0. I'll be including sets and timer_data as well.

This should resolve this bug too.

**Comment by dbhowell** [comment]
Should be resolved now, finally.
